# test.py
from config_simple import DOCKER, KAFKA_BOOTSTRAP_SERVERS, POSTGRES_HOST

print(f"DOCKER: {DOCKER}")
print(f"KAFKA_BOOTSTRAP_SERVERS: {KAFKA_BOOTSTRAP_SERVERS}")
print(f"POSTGRES_HOST: {POSTGRES_HOST}")